export type Modality='Blood test'|'Body composition'|'MRI report';
export type Observation={id:string;name:string;value:string;unit:string;reference?:{low:number;high:number};topic:'Metabolic health'|'Body composition';verified:boolean};
export type DiagnosticDocument={id:string;name:string;modality:Modality;date:string;patient:string;method:string;page:number;excerpt:string;observations:Observation[];verified:boolean};
export const DEMO_DOCUMENTS:DiagnosticDocument[]=[
 {id:'blood',name:'Metabolic blood panel',modality:'Blood test',date:'2026-08-20',patient:'DEMO-001',method:'Fictional laboratory · fasting status not supplied',page:1,excerpt:'SYNTHETIC EXAMPLE — not a patient record. Glucose 108 mg/dL (reference 70–99). Triglycerides 182 mg/dL (reference 0–149). ALT 42 U/L (reference 0–40). Reference intervals are fictional inputs for testing, not clinical rules.',verified:false,observations:[{id:'glucose',name:'Glucose',value:'108',unit:'mg/dL',reference:{low:70,high:99},topic:'Metabolic health',verified:false},{id:'triglycerides',name:'Triglycerides',value:'182',unit:'mg/dL',reference:{low:0,high:149},topic:'Metabolic health',verified:false},{id:'alt',name:'ALT',value:'42',unit:'U/L',reference:{low:0,high:40},topic:'Metabolic health',verified:false}]},
 {id:'body',name:'Body-composition assessment',modality:'Body composition',date:'2026-08-22',patient:'DEMO-001',method:'Fictional bioelectrical impedance device; model unspecified',page:1,excerpt:'SYNTHETIC EXAMPLE — not a patient record. Body fat 29%. Skeletal muscle mass 28.6 kg. Visceral fat rating 13, a device-specific estimate. No reference ranges or device model supplied.',verified:false,observations:[{id:'fat',name:'Body fat',value:'29',unit:'%',topic:'Body composition',verified:false},{id:'muscle',name:'Skeletal muscle mass',value:'28.6',unit:'kg',topic:'Body composition',verified:false},{id:'visceral',name:'Visceral fat rating',value:'13',unit:'device rating',topic:'Body composition',verified:false}]},
 {id:'mri',name:'Abdominal MRI · written report',modality:'MRI report',date:'2026-08-25',patient:'DEMO-001',method:'Synthetic radiologist narrative; no image processing',page:1,excerpt:'SYNTHETIC EXAMPLE — not a patient record. Impression: mild hepatic steatosis. No focal liver lesion described. No quantitative liver-fat fraction or visceral-fat volume reported.',verified:false,observations:[]}
];
export function resultStatus(o:Observation){if(!o.value.trim()||!Number.isFinite(Number(o.value)))return 'Needs a numeric value';if(!o.reference)return 'No supplied reference interval';const n=Number(o.value);return n<o.reference.low?'Below supplied interval':n>o.reference.high?'Above supplied interval':'Within supplied interval';}
export function ready(documents:DiagnosticDocument[]){return documents.length>0&&new Set(documents.map(d=>d.patient)).size===1&&documents.every(d=>d.verified&&d.observations.every(o=>o.verified&&Number.isFinite(Number(o.value))&&o.value.trim()!==''));}
export function connectedFindings(documents:DiagnosticDocument[]){const ids=new Set(documents.map(d=>d.id));const findings:{title:string;text:string;sources:string[]}[]=[];
 if(ids.has('blood')&&ids.has('mri'))findings.push({title:'Blood results and liver imaging need joint review',text:'The blood panel and the written MRI report offer different information about the same assessment. The MRI narrative describes liver fat; blood measurements do not independently establish its cause or severity. Review both with the clinical history.',sources:['blood','mri']});
 if(ids.has('body')&&ids.has('mri'))findings.push({title:'Liver fat and a visceral-fat rating are different measurements',text:'The device’s visceral-fat rating cannot be converted into the MRI finding. The written MRI describes liver fat but does not quantify visceral fat. Keep these findings separate within the overall assessment.',sources:['body','mri']});
 if(ids.has('blood')&&ids.has('body'))findings.push({title:'Measurements taken on different dates',text:'Blood and body-composition results can be reviewed together, but they were collected on different days. Fasting status, hydration, device method and medication history are not supplied. These records do not establish a trend or a causal relationship.',sources:['blood','body']});
 return findings;
}
export function escapeHtml(v:string){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
