import {extractResults,repeatedMeasurements,referenceLabel,type ImportedReport} from './report-import';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportHtml(reports:ImportedReport[],label:string,context:string,notes:string){
 const all=reports.flatMap(extractResults),flagged=all.filter(r=>r.status!=='Within printed range');
 const table=(r:typeof all)=>`<table><thead><tr><th>Measurement</th><th>Result</th><th>Printed range</th><th>Source</th></tr></thead><tbody>${r.map(x=>`<tr><td>${escape(x.name)}<small>${escape(x.status)}</small></td><td>${x.value} ${escape(x.unit)}</td><td>${escape(referenceLabel(x))}</td><td>${escape(x.source)} · p. ${x.page}<small>${escape(x.date||'Date not supplied')}</small></td></tr>`).join('')}</tbody></table>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Kamura appointment summary</title><style>@page{size:A4;margin:18mm}body{font:13px/1.65 Arial,sans-serif;color:#193f38;max-width:900px;margin:35px auto;padding:0 20px}header{border-bottom:2px solid #00796d;padding-bottom:20px}h1{font:36px Georgia,serif}h2{font:24px Georgia,serif;margin-top:30px;break-after:avoid}small{display:block;color:#526b61;font-size:11px}table{border-collapse:collapse;width:100%;margin:15px 0;font-size:12px}td,th{text-align:left;border-bottom:1px solid #d6e2da;padding:10px;vertical-align:top}th{background:#edf5ef}tr{break-inside:avoid}.source{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.summary{padding:16px;background:#edf5ef}.print{padding:12px 20px;background:#00796d;color:white;border:0;border-radius:20px;cursor:pointer}@media print{.print{display:none}body{margin:0;padding:0}.appendix{break-before:page}}</style></head><body><button class="print" onclick="window.print()">Print / Save as PDF</button><header><small>KAMURA · APPOINTMENT PREPARATION</small><h1>${escape(label||'Your health, together.')}</h1><p>${reports.length} reports · ${all.length} recognised measurements · ${flagged.length} outside printed ranges</p></header><p class="summary">This document combines selected findings and printed-range comparisons. Missing or unrecognised results remain in the extracted appendix and need source review.</p><h2>Your context</h2><p>${escape(context||'Not supplied.')}</p><h2>Results to discuss</h2>${flagged.length?table(flagged):'<p>No out-of-range result recognised. This does not establish that all results are normal.</p>'}<h2>Measurements across reports</h2>${repeatedMeasurements(reports).map(g=>`<h3>${escape(g[0].name)}</h3>${table(g)}`).join('')||'<p>No directly matching names and units across sources.</p>'}<p>Dates order the records; matching units alone do not establish comparable lab methods.</p><h2>Your questions and next steps</h2><p class="source">${escape(notes||'Discuss source conclusions, missing information and follow-up timing with your clinician.')}</p>${reports.map(r=>`<h2>${escape(r.name)}</h2><small>${escape(r.kind)} · ${escape(r.date||'Date not supplied')}</small><p class="source">${escape(r.findings||'No conclusion selected. Review the extracted source appendix.')}</p>${table(extractResults(r))}`).join('')}<section class="appendix"><h2>Extracted source appendix</h2><p>Text recognition can omit or misread content. Keep the original documents with this summary.</p>${reports.map(r=>`<h3>${escape(r.name)}</h3>${r.pages.map(p=>`<h4>Page / section ${p.number}${p.ocr?' · OCR':''}</h4><div class="source">${escape(p.text)}</div>`).join('')}`).join('')}</section></body></html>`;
}
export function printReport(reports:ImportedReport[],label:string,context:string,notes:string){const win=window.open('','_blank');if(!win)throw Error('Allow the print window to open, then try again.');win.opener=null;win.document.write(reportHtml(reports,label,context,notes));win.document.close();}
export async function exportReport(reports:ImportedReport[],label:string,context:string,notes:string){
 const {Document,Packer,Paragraph,HeadingLevel,TextRun,Table,TableRow,TableCell,WidthType}=await import('docx');
 const p=(text:string)=>new Paragraph({children:[new TextRun(text)],spacing:{after:120}});
 const h=(text:string)=>new Paragraph({text,heading:HeadingLevel.HEADING_2,spacing:{before:260,after:140}});
 const all=reports.flatMap(extractResults),flagged=all.filter(x=>x.status!=='Within printed range');
 const table=(rows:typeof all)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[['Measurement','Result','Printed range','Source / date'],...rows.map(x=>[x.name+' · '+x.status,`${x.value} ${x.unit}`,referenceLabel(x),`${x.source}, p. ${x.page} · ${x.date||'Date not supplied'}`])].map((row,i)=>new TableRow({tableHeader:i===0,children:row.map(t=>new TableCell({children:[p(t)]}))}))});
 const content=[new Paragraph({text:'KAMURA',heading:HeadingLevel.TITLE}),new Paragraph({text:label||'Your health, together.',heading:HeadingLevel.HEADING_1}),p(`Appointment summary · ${reports.length} source reports · ${all.length} recognised measurements`),p('Printed-range comparison and selected findings. Unrecognised results require review of the original documents.'),h('Your context'),p(context||'Not supplied.'),h('Results to discuss'),...(flagged.length?[table(flagged)]:[p('No out-of-range result recognised. This is not an all-clear.')]),h('Measurements across reports'),...repeatedMeasurements(reports).flatMap(g=>[p(g[0].name),table(g)]),p('Records are ordered by supplied date. Confirm assay, units and timing before interpreting a trend.'),h('Your questions and next steps'),p(notes||'Discuss source conclusions, missing information and follow-up timing with your clinician.'),...reports.flatMap(r=>[h(r.name),p(`${r.kind} · ${r.date||'Date not supplied'}`),p(r.findings||'No conclusion selected; see extracted appendix.'),...(extractResults(r).length?[table(extractResults(r))]:[])]),h('Extracted source appendix'),p('Text recognition can omit or misread content. Keep the original documents with this summary.'),...reports.flatMap(r=>[h(r.name),...r.pages.flatMap(page=>[p(`Page / section ${page.number}${page.ocr?' · OCR':''}`),...page.text.split('\n').map(p)])])];
 const blob=await Packer.toBlob(new Document({sections:[{properties:{},children:content}]}));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Kamura-appointment-summary-${new Date().toISOString().slice(0,10)}.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);
}
