export type ImportedPage={number:number;text:string;ocr:boolean};
export type ReportKind='Blood test'|'Body composition'|'Imaging report'|'Other';
export type ImportedReport={id:string;name:string;kind:ReportKind;date:string;pages:ImportedPage[];reviewed:boolean;findings:string;hash:string};
export type ExtractedResult={name:string;value:number;unit:string;low:number;high:number;status:'Above printed range'|'Below printed range'|'Within printed range';source:string;page:number;line:string};
// Deliberately conservative: ambiguous columns and one-sided cut-offs stay in source text.
export function extractResults(report:ImportedReport):ExtractedResult[]{const results:ExtractedResult[]=[];for(const page of report.pages)for(const raw of page.text.split('\n')){const line=raw.trim();const match=line.match(/^([A-Za-z][A-Za-z ()/%.,-]{1,65}?)\s*[,;\t ]+\s*(-?\d+(?:\.\d+)?)\s*[,;\t ]+\s*([a-zA-Zµμ%][a-zA-Zµμ%\d/^.-]*)\s*[,;\t ]+\s*(?:\(?\s*(?:reference(?: range)?|range)\s*[:=]?\s*)?(-?\d+(?:\.\d+)?)\s*[-–—]\s*(-?\d+(?:\.\d+)?)\s*\)?\s*$/i);if(!match)continue;const [,name,v,unit,l,h]=match;const value=Number(v),low=Number(l),high=Number(h);if(low>high||![value,low,high].every(Number.isFinite))continue;results.push({name:name.trim(),value,unit,low,high,status:value<low?'Below printed range':value>high?'Above printed range':'Within printed range',source:report.name,page:page.number,line});}return results;}
export function inferKind(text:string):ReportKind{if(/\b(MRI|radiology|impression|CT scan|ultrasound)\b/i.test(text))return 'Imaging report';if(/\b(inbody|body composition|skeletal muscle|body fat|DEXA)\b/i.test(text))return 'Body composition';if(/\b(haemoglobin|hemoglobin|glucose|cholesterol|blood test|triglycerides)\b/i.test(text))return 'Blood test';return 'Other';}
export function repeatedMeasurements(reports:ImportedReport[]){const groups=new Map<string,ExtractedResult[]>();for(const r of reports)for(const o of extractResults(r)){const key=o.name.toLowerCase()+'|'+o.unit;groups.set(key,[...(groups.get(key)||[]),o]);}return [...groups.values()].filter(g=>new Set(g.map(x=>x.source)).size>1);}
export function reportText(report:ImportedReport){return report.pages.map(p=>`PAGE ${p.number}${p.ocr?' · OCR':''}\n${p.text}`).join('\n\n');}
