'use client';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import SaveButton from '@/components/kamura/SaveButton';
import {DEFAULT_VISIBLE,type Atlas,type SceneState} from '@/components/body-explorer/anatomy';
import s from './AbdominalLab.module.css';
const Scene=dynamic(()=>import('@/components/body-explorer/scene'),{ssr:false});
const chapters=['Locate the fat','Follow the signal','Explore the evidence','Take it to a consultation'];
const layers=[{name:'Subcutaneous fat',text:'The fat beneath the skin, outside the abdominal muscle wall. It is a different compartment from the fat surrounding internal organs.',color:'#e6bc72'},{name:'Abdominal wall',text:'Muscle and connective tissue form the wall around the abdominal cavity. The wall separates the outer fat layer from the internal compartment.',color:'#bc786e'},{name:'Visceral fat',text:'Fat within the abdomen, around internal organs. This is the compartment measured in the tesamorelin trial below—not total body fat.',color:'#dd973c'}];
const signals=[{title:'Pituitary: receive the signal',text:'Tesamorelin mimics growth-hormone-releasing hormone (GHRH). It acts at GHRH receptors on pituitary cells, stimulating the body’s own growth-hormone release.',match:'pituitary'}, {title:'Bloodstream: carry growth hormone',text:'Growth hormone enters the circulation and acts on multiple tissues. It also stimulates IGF-1 production, including in the liver. This is a hormonal pathway, not a drug travelling directly to belly fat.',match:'liver'}, {title:'Adipose tissue: alter fat metabolism',text:'Growth hormone influences fat mobilisation. Whether a treatment changes a person’s fat compartment is an outcome to measure; the mechanism alone does not establish the benefit.',match:'adipose tissue not represented'}];
const questions=['Does the studied population match my situation?','Which measurement would answer my question about abdominal fat?','What benefits, risks and alternatives matter in my case?','What would we monitor, and when would we reassess?'];
export default function AbdominalLab(){
 const [chapter,setChapter]=useState(0),[layer,setLayer]=useState(2),[cutaway,setCutaway]=useState(false),[step,setStep]=useState(0),[endpoint,setEndpoint]=useState(false),[picked,setPicked]=useState<string[]>([questions[0]]),[question,setQuestion]=useState(''),[quiz,setQuiz]=useState(''),[atlas,setAtlas]=useState<Atlas|null>(null),[error,setError]=useState(''),[progress,setProgress]=useState(0);
 const [scene,setScene]=useState<SceneState>({visible:DEFAULT_VISIBLE.filter(x=>x!=='muscular'),selected:[],isolate:false,explode:0,rotate:false,view:'front',reset:0});
 useEffect(()=>{const a=new AbortController();fetch('/body-models/atlas.json',{signal:a.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setAtlas).catch(e=>{if(e.name!=='AbortError')setError('Anatomy could not load. Explore the tissue cross-section instead.');});return()=>a.abort();},[]);
 function go(i:number){setChapter(i);if(i===1){setCutaway(false);focus(0);}if(i===2)setCutaway(true);}
 function focus(i:number){setStep(i);setScene(v=>({...v,selected:atlas?.parts.filter(p=>p.name.toLowerCase().includes(signals[i].match)).map(p=>p.id)||[]}));}
 const notes=['Abdominal fat · Kamura',...picked.map(q=>'• '+q),...(question.trim()?['• '+question.trim()]:[]),'Study: https://pubmed.ncbi.nlm.nih.gov/18057338/','Learning guide: https://kamuralife.com/peptides/tesamorelin'].join('\n');
 return <article className={s.lab}><nav className={s.rail} aria-label="Abdominal fat learning journey"><Link href="/peptides/directory">← Therapy library</Link><p>THE BODY LAB</p><h2>A closer look<br/>at abdominal fat.</h2>{chapters.map((x,i)=><button key={x} aria-current={chapter===i?'step':undefined} onClick={()=>go(i)}><span>0{i+1}</span>{x}</button>)}<Link href="/body?t=tesamorelin">All anatomy tools ↗</Link></nav>
 <section className={s.visual} aria-label="Interactive abdominal anatomy"><div className={s.visualHeading}><small>KAMURA / EXPLORE WITH PURPOSE</small><h2>{cutaway?'Beneath the abdominal wall':chapter===1?signals[step].title:'One body. Different fat compartments.'}</h2><div className={s.switch}><button aria-pressed={!cutaway} onClick={()=>setCutaway(false)}>3D body</button><button aria-pressed={cutaway} onClick={()=>setCutaway(true)}>Tissue cross-section</button></div></div>
 {cutaway?<div className={s.slice}><svg viewBox="0 0 600 480" role="img" aria-label="Schematic abdominal cross-section: subcutaneous fat outside the muscle wall and visceral fat around simplified bowel loops"><defs><radialGradient id="fat"><stop stopColor="#fbe8ad"/><stop offset="1" stopColor="#dca654"/></radialGradient></defs><ellipse cx="300" cy="240" rx="259" ry="191" fill="#eed8c0" stroke="#bca78f" strokeWidth="3"/><ellipse cx="300" cy="240" rx="245" ry="177" fill="url(#fat)" opacity={layer===0?1:.45}/><ellipse cx="300" cy="240" rx="207" ry="142" fill="#bc786e" opacity={layer===1?1:.65}/><ellipse cx="300" cy="240" rx="187" ry="121" fill="#f9edd4"/>{Array.from({length:28},(_,i)=>{const a=i*Math.PI*2/28;return <ellipse key={i} cx={300+Math.cos(a)*146} cy={240+Math.sin(a)*82} rx="24" ry="19" fill="#dd973c" opacity={layer===2?1:.3}/>;})}<g fill="none" stroke="#c48579" strokeWidth="23" strokeLinecap="round"><path d="M230 190 C350 157 382 215 276 218 S221 280 341 254 S352 313 259 291"/></g><ellipse cx="300" cy="341" rx="29" ry="23" fill="#ede7db" stroke="#b5ab9d" strokeWidth="3"/><text x="300" y="26" textAnchor="middle" fill="#526d64" fontSize="13">FRONT OF ABDOMEN</text><text x="300" y="462" textAnchor="middle" fill="#526d64" fontSize="13">BACK · SIMPLIFIED CROSS-SECTION</text></svg><div className={s.legend}>{layers.map((x,i)=><button key={x.name} aria-pressed={layer===i} onClick={()=>setLayer(i)}><i style={{background:x.color}}/>{x.name}</button>)}</div></div>:<><div className={s.canvas}>{atlas&&<Scene atlas={atlas} state={scene} embedded onProgress={setProgress} onError={setError} onSelect={id=>setScene(v=>({...v,selected:[id]}))}/>}</div>{(progress<100||error)&&<p className={s.loading} role="status">{error||`Loading anatomy · ${progress}%`}</p>}<div className={s.controls}><button aria-pressed={scene.rotate} onClick={()=>setScene(v=>({...v,rotate:!v.rotate}))}>{scene.rotate?'Pause':'Rotate'}</button><button aria-pressed={scene.visible.includes('muscular')} onClick={()=>setScene(v=>({...v,visible:v.visible.includes('muscular')?v.visible.filter(x=>x!=='muscular'):[...v.visible,'muscular']}))}>Muscle layer</button><button onClick={()=>setScene(v=>({...v,reset:v.reset+1,view:'front'}))}>Reset</button></div></>}
 <p className={s.caption}>{cutaway?'Illustrated tissue compartments · not a scan or a treatment simulation':'Drag to rotate · Scroll to zoom · Male reference anatomy'}<br/>{chapter===1?'Highlights locate organs; receptors and fat compartments are not in the 3D model.':'Switch views to connect whole-body anatomy with the tissue layers.'}</p></section>
 <aside className={s.info}><small>PREVENTIVE HEALTH / GUIDED EXPLORATION</small><h1>Tesamorelin & abdominal fat</h1><p className={s.intro}>Understand where fat sits, how the hormone signal works and what a clinical trial actually measured.</p>
 <section hidden={chapter!==0}><h2>Which fat are we talking about?</h2><div className={s.options}>{layers.map((x,i)=><button key={x.name} aria-pressed={layer===i} onClick={()=>{setLayer(i);setCutaway(true);}}>{x.name} ↗</button>)}</div><div className={s.card} aria-live="polite"><small>SELECTED TISSUE</small><h3>{layers[layer].name}</h3><p>{layers[layer].text}</p></div><h3>A useful distinction</h3><p>Waist size does not separate these compartments. The trial used CT imaging to measure visceral adipose tissue. A smaller waist and a measured change in visceral fat are different outcomes.</p><fieldset className={s.quiz}><legend>Check your understanding</legend><p>Which compartment sits outside the abdominal muscle wall?</p>{['Subcutaneous fat','Visceral fat'].map(x=><button key={x} aria-pressed={quiz===x} onClick={()=>setQuiz(x)}>{x}</button>)}{quiz&&<p role="status">{quiz==='Subcutaneous fat'?'Exactly. It lies beneath the skin, outside the muscle wall.':'Look again at the outer yellow ring: that is subcutaneous fat. Visceral fat sits inside.'}</p>}</fieldset></section>
 <section hidden={chapter!==1}><h2>Follow the hormonal signal</h2>{signals.map((x,i)=><button className={s.signal} aria-pressed={step===i} key={x.title} onClick={()=>{setCutaway(false);focus(i);}}><span>0{i+1}</span>{x.title}</button>)}<div className={s.card} aria-live="polite"><h3>{signals[step].title}</h3><p>{signals[step].text}</p></div><button className={s.secondary} onClick={()=>focus((step+1)%3)}>Next signal →</button><p>These steps explain a mechanism. The next chapter separates that mechanism from the measured clinical result.</p></section>
 <section hidden={chapter!==2}><h2>What changed in the study?</h2><p>In a 26-week randomised trial, 412 adults with HIV and abdominal fat accumulation received tesamorelin or placebo.</p><div className={s.switch}><button aria-pressed={!endpoint} onClick={()=>setEndpoint(false)}>Baseline</button><button aria-pressed={endpoint} onClick={()=>setEndpoint(true)}>Week 26</button></div><div className={s.chart} aria-live="polite"><p>Visceral fat · baseline normalised to 100</p>{[{name:'Tesamorelin',value:endpoint?84.8:100,result:'−15.2%'},{name:'Placebo',value:endpoint?105:100,result:'+5.0%'}].map((x,i)=><div key={x.name}><label>{x.name}<strong>{endpoint?x.result:'Baseline'}</strong></label><div className={s.track}><div style={{width:`${x.value/1.1}%`,background:i?'#9bab9d':'#007b70'}}/></div></div>)}</div><p>These are reported group changes at the endpoint, not an individual forecast or a week-by-week trajectory.</p><div className={s.card}><h3>What this answers</h3><p>Tesamorelin reduced measured visceral fat in this study population. It does not establish the same result for general weight loss, every body type or a specific person.</p></div><a href="https://pubmed.ncbi.nlm.nih.gov/18057338/" target="_blank" rel="noreferrer">Read the original trial · NEJM, 2007 ↗</a></section>
 <section hidden={chapter!==3}><h2>Leave with better questions</h2><p>Select the questions you want to discuss. Add your own and save the note to My Kamura.</p>{questions.map(q=><label className={s.question} key={q}><input type="checkbox" checked={picked.includes(q)} onChange={()=>setPicked(v=>v.includes(q)?v.filter(x=>x!==q):[...v,q])}/>{q}</label>)}<label className={s.custom}>Your question<textarea maxLength={1500} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would you like your clinician to explain?"/></label><SaveButton key={notes} item={{id:`plan:abdominal-fat:${encodeURIComponent(notes)}`,kind:'Learning plan',title:'My abdominal-fat consultation',href:'/peptides/tesamorelin',notes}}/><p className={s.small}>Saved in this browser. Find your note under My Kamura → Saved.</p><Link href="/my/saved">Open saved notes ↗</Link></section>
 {chapter<3&&<button className={s.next} onClick={()=>go(chapter+1)}>{chapters[chapter+1]} →</button>}<details className={s.sources}><summary>Sources & anatomy credits</summary><a href="https://pubmed.ncbi.nlm.nih.gov/18057338/">Falutz et al. · Clinical trial, 2007 ↗</a><a href="https://pubmed.ncbi.nlm.nih.gov/25358450/">Tesamorelin pharmacology, 2015 ↗</a><Link href="/body-models/ATTRIBUTION.md">BodyParts3D / DBCLS anatomy credits ↗</Link><p>Study results checked 13 September 2026. Tissue illustration is schematic and does not encode fat quantity.</p></details></aside></article>;
}
