import Link from 'next/link';
import {ArrowUpRight,Activity,Brain,Heart,MoveUpRight} from 'lucide-react';
import HomeBody from './HomeBody';
import s from './Kamura.module.css';
export default function Home(){return <div className={s.page}><HomeBody/><div className={s.container}>
 <nav className={s.strip} aria-label="Discover Kamura"><Link href="/learn"><div><strong>Understand the science</strong><small>Therapies, mechanisms & research</small></div><ArrowUpRight/></Link><Link href="/explore"><div><strong>Find your care</strong><small>Explore care & wellness services</small></div><ArrowUpRight/></Link><Link href="/classes"><div><strong>Make room for movement</strong><small>Classes & studios across the UAE</small></div><ArrowUpRight/></Link></nav>
 <section className={s.section}><div className={s.sectionHead}><div><span className={s.eyebrow}>Follow your curiosity</span><h2>A little understanding.<br/>A different perspective.</h2></div><Link href="/learn">Explore the learning library ↗</Link></div><div className={s.grid}>{[{title:'Recovery, explained',text:'Explore muscle and connective tissue, repair pathways and the research behind BPC-157.',href:'/body?t=bpc-157',Icon:Activity,label:'BODY & RECOVERY'},{title:'Hormones in context',text:'Follow testosterone signalling and feedback. Connect the mechanism to the evidence.',href:'/body?t=trt',Icon:Brain,label:'HORMONES & HEALTH'},{title:'Beyond body weight',text:'Explore visceral fat and see what tesamorelin studies actually measured.',href:'/body?t=tesamorelin',Icon:Heart,label:'METABOLIC HEALTH'}].map(c=><Link href={c.href} key={c.title} className={s.card}><div className={s.cardArt}><c.Icon/></div><div className={s.cardBody}><small>{c.label}</small><h3>{c.title}</h3><p>{c.text}</p><span>Open the explanation ↗</span></div></Link>)}</div></section>
 <section className={s.feature}><div><span className={s.eyebrow}>My Kamura</span><h2>Build a rhythm<br/>you can return to.</h2><p>Keep your learning, class practice and personal check-ins together. Start exploring in guest mode, or sign in to your account.</p><div className={s.buttons}><Link href="/my" className={s.primary}>Open My Kamura <ArrowUpRight size={18}/></Link></div></div><div className={s.miniPlan}><span>YOUR SPACE TO KEEP GOING</span><p>01 &nbsp; Continue your learning</p><p>02 &nbsp; Plan your next practice</p><p>03 &nbsp; Reflect on how you feel</p><Link href="/my/classes" className={s.buttons}>Explore your practice <MoveUpRight size={18}/></Link></div></section>
 <section className={s.section}><div className={s.sectionHead}><div><span className={s.eyebrow}>Connect knowledge to real life</span><h2>Find your people.<br/>Find your practice.</h2></div></div><div className={s.grid}>{[{title:'Classes & studios',text:'Yoga, Pilates, breathwork and more. Explore studios by discipline and emirate.',href:'/classes',label:'MOVE & RESTORE'},{title:'Care & services',text:'Explore the kinds of care Kamura is bringing together. Provider booking is in development.',href:'/explore',label:'FIND CARE'},{title:'Events & ideas',text:'Discover wellness events, workshops and conversations around longevity.',href:'/events',label:'MEET & LEARN'}].map(c=><Link href={c.href} key={c.href} className={s.card}><div className={s.cardBody}><small>{c.label}</small><h3>{c.title}</h3><p>{c.text}</p><span>Explore ↗</span></div></Link>)}</div></section>
 </div></div>;}
