import Link from 'next/link';
import {ArrowUpRight,Activity,Brain,Heart,MoveUpRight} from 'lucide-react';
import HomeBody from './HomeBody';
import s from './Kamura.module.css';
export default function Home(){return <div className={s.page}><HomeBody/><div className={s.container}>
 <section className={s.homeIntroduction}><span className={s.eyebrow}>WHAT IS KAMURA?</span><h2>Your place to understand health<br/>and explore what comes next.</h2><p>Start with a question about your body. Follow a visual explanation, read the supporting research, and save the questions you want to discuss with a clinician. When you’re ready, explore care providers, studios and wellness events.</p></section><nav className={s.strip} aria-label="Discover Kamura"><Link href="/learn"><div><strong>Understand the science</strong><small>Therapies, mechanisms & research</small></div><ArrowUpRight/></Link><Link href="/explore"><div><strong>Find your care</strong><small>Explore care & wellness services</small></div><ArrowUpRight/></Link><Link href="/classes"><div><strong>Make room for movement</strong><small>Classes & studios across the UAE</small></div><ArrowUpRight/></Link></nav>
 <section className={s.section}><div className={s.sectionHead}><div><span className={s.eyebrow}>START WITH A QUESTION</span><h2>What would you like<br/>to understand?</h2></div><Link href="/learn">Explore the learning library ↗</Link></div><div className={s.grid}>{[{title:'How does tissue repair work?',text:'Explore muscle and connective tissue, repair pathways and the research behind BPC-157.',href:'/peptides/bpc-157',Icon:Activity,label:'BODY & RECOVERY'},{title:'How do hormones send signals?',text:'Follow testosterone signalling and feedback. Connect the mechanism to the evidence.',href:'/body?t=trt',Icon:Brain,label:'HORMONES & HEALTH'},{title:'What is visceral fat?',text:'Explore visceral fat and see what tesamorelin studies actually measured.',href:'/peptides/tesamorelin',Icon:Heart,label:'METABOLIC HEALTH'}].map(c=><Link href={c.href} key={c.title} className={s.card}><div className={s.cardArt}><c.Icon/></div><div className={s.cardBody}><small>{c.label}</small><h3>{c.title}</h3><p>{c.text}</p><span>Open the explanation ↗</span></div></Link>)}</div></section>
 <section className={s.feature}><div><span className={s.eyebrow}>My Kamura</span><h2>Keep the questions.<br/>Continue the learning.</h2><p>Save therapies and discussion questions in My Kamura. Revisit your collection and export a consultation note. Your saved collection stays in this browser, including when signed in.</p><div className={s.buttons}><Link href="/my" className={s.primary}>Open My Kamura <ArrowUpRight size={18}/></Link></div></div><div className={s.miniPlan}><span>YOUR SPACE TO KEEP GOING</span><p>01 &nbsp; Save a topic that matters to you</p><p>02 &nbsp; Collect your consultation questions</p><p>03 &nbsp; Export a note to take with you</p><Link href="/my/saved" className={s.buttons}>Open your saved collection <MoveUpRight size={18}/></Link></div></section>
 <section className={s.section}><div className={s.sectionHead}><div><span className={s.eyebrow}>Connect knowledge to real life</span><h2>Find your people.<br/>Find your practice.</h2></div></div><div className={s.grid}>{[{title:'Classes & studios',text:'Yoga, Pilates, breathwork and more. Explore studios by discipline and emirate.',href:'/classes',label:'MOVE & RESTORE'},{title:'Care & services',text:'Explore the kinds of care Kamura is bringing together. Provider booking is in development.',href:'/explore',label:'FIND CARE'},{title:'Events & ideas',text:'Discover wellness events, workshops and conversations around longevity.',href:'/events',label:'MEET & LEARN'}].map(c=><Link href={c.href} key={c.href} className={s.card}><div className={s.cardBody}><small>{c.label}</small><h3>{c.title}</h3><p>{c.text}</p><span>Explore ↗</span></div></Link>)}</div></section>
 </div></div>;}
