 'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useSaved,updateSaved,type SavedItem} from './saved';
import s from './Saved.module.css';
export function SavedSummary(){const items=useSaved();return <Link href="/my/saved" className={s.banner}><span><strong>Your saved discoveries</strong><small>{items.length?`${items.length} saved · pick up where you left off`:'Keep therapies, care, studios and learning plans together'}</small></span><span aria-hidden="true">↗</span></Link>;}
export default function SavedCollection(){const items=useSaved();const [kind,setKind]=useState('All'),[query,setQuery]=useState(''),[status,setStatus]=useState('');const filtered=items.filter(x=>(kind==='All'||x.kind===kind)&&x.title.toLowerCase().includes(query.toLowerCase()));
function change(fn:(items:SavedItem[])=>SavedItem[]){setStatus(updateSaved(fn)?'Changes saved on this browser.':'Your browser could not save the change.');}
function download(item:SavedItem){const body=`${item.title}\n${item.notes||''}\n\nOpen: ${new URL(item.href,location.origin).href}\n\nDiscussed questions:\n${(item.checked||[]).join('\n')}`;const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='kamura-learning-plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Learning plan exported.');}
return <><header className={s.intro}><span className={s.kind}>MY KAMURA / SAVED</span><h1>Turn curiosity into a next step.</h1><p>Your reading, care shortlist and discussion questions in one place. Saved on this browser only, including when signed in. Export a learning plan to keep a copy.</p></header><div className={s.filters}><input aria-label="Search saved items" placeholder="Search your collection" value={query} onChange={e=>setQuery(e.target.value)}/>{['All','Therapy','Care','Studio','Learning plan'].map(x=><button className={s.action} key={x} aria-pressed={kind===x} onClick={()=>setKind(x)}>{x}</button>)}</div><p className={s.status} role="status">{status||`${filtered.length} saved items`}</p>{!filtered.length?<section className={s.empty}><h2>{items.length?'No matches in your collection.':'Start with something you want to understand.'}</h2><p>Save a therapy in the body explorer, a provider in Find care, or a studio in Classes.</p><div className={s.actions}><Link href="/body" className={s.action}>Explore therapies ↗</Link><Link href="/explore" className={s.action}>Find care ↗</Link><Link href="/classes" className={s.action}>Explore classes ↗</Link></div></section>:<div className={s.grid}>{filtered.map(item=>{const questions=(item.notes||'').split('\n').filter(x=>x.startsWith('•'));const checked=item.checked||[];return <article key={item.id} className={s.card}><span className={s.kind}>{item.kind}</span><h2>{item.title}</h2>{item.notes&&<p className={s.notes}>{item.notes.split('\n').filter(x=>!x.startsWith('•')).join('\n')}</p>}{questions.length>0&&<><p>{questions.filter(q=>checked.includes(q)).length} of {questions.length} questions discussed</p><progress aria-label="Questions discussed" value={questions.filter(q=>checked.includes(q)).length} max={questions.length}/>{questions.map(q=><label className={s.question} key={q}><input type="checkbox" checked={checked.includes(q)} onChange={()=>change(all=>all.map(x=>x.id===item.id?{...x,checked:(x.checked||[]).includes(q)?(x.checked||[]).filter(v=>v!==q):[...(x.checked||[]),q]}:x))}/><span>{q.slice(1).trim()}</span></label>)}</>}<div className={s.actions}><a className={s.action} href={item.href} {...(item.href.startsWith('https:')?{target:'_blank',rel:'noopener noreferrer'}:{})}>{item.kind==='Studio'?'Visit studio ↗':item.kind==='Care'?'View provider ↗':'Continue learning ↗'}</a>{item.notes&&<button className={s.action} onClick={()=>download(item)}>Export questions</button>}<button className={s.action} onClick={()=>change(all=>all.filter(x=>x.id!==item.id))} aria-label={`Remove ${item.title}`}>Remove</button></div></article>;})}</div>}</>;}
