 'use client';
import {peptideContexts} from '@/lib/peptide-learning';
import {useEffect,useState} from 'react';
import catalogue from '@/data/therapy-explorer.json';
import {Evidence,Mechanism} from './LearningTools';
import s from './LearningTools.module.css';
type Therapy=typeof catalogue[number];
export function PathwayMap({therapy}:{therapy:Therapy}){const [active,setActive]=useState(0),[playing,setPlaying]=useState(false);const context=peptideContexts[therapy.id];const steps=context?context.steps.map(x=>x.title):therapy.pathway;
useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(active>=steps.length-1)setPlaying(false);else setActive(active+1);},3000);return()=>clearTimeout(timer);},[active,playing,steps.length]);
return <section className={s.pathway}><div className={s.controls}><span className={s.kicker}>FOLLOW THE SIGNAL · SCHEMATIC</span><button onClick={()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setActive(v=>(v+1)%steps.length);return;}if(active===steps.length-1)setActive(0);setPlaying(v=>!v);}}>{playing?'Pause signal':'Follow signal'}</button></div><div className={s.nodes}>{steps.map((step,i)=><button key={i} className={`${s.node} ${active===i?s.activeNode:''}`} aria-pressed={active===i} onClick={()=>{setActive(i);setPlaying(false);}}><span>{String(i+1).padStart(2,'0')}</span><strong>{step}</strong>{i<steps.length-1&&<i aria-hidden="true">→</i>}</button>)}</div><div className={s.signalDetail} aria-live="polite"><span>STEP {active+1} / {steps.length}</span><h3>{steps[active]}</h3><p>{context?context.steps[active].plain:active===0?therapy.what:active===steps.length-1?therapy.scope:therapy.mechanism}</p></div></section>;}
const chapters=['The question','Follow the signal','See the process','Read the evidence'];
export default function Consultation({therapy}:{therapy:Therapy}){const [chapter,setChapter]=useState(0);return <div className={s.consult}><div className={s.consultTop}><span className={s.kicker}>CONSULTATION / {therapy.name}</span><span>{chapter+1} / {chapters.length}</span></div><nav className={s.chapters} aria-label="Presentation chapters">{chapters.map((x,i)=><button key={x} aria-current={chapter===i?'step':undefined} onClick={()=>setChapter(i)}>{String(i+1).padStart(2,'0')} · {x}</button>)}</nav><main className={s.slide} key={chapter}>{chapter===0?<><span className={s.kicker}>{therapy.category}</span><h3>{therapy.name}</h3><p className={s.bigCopy}>{therapy.what}</p><div className={s.questionBox}><span>START THE CONVERSATION</span><h4>What would we want to understand or measure?</h4><p>{therapy.regions.map(x=>x.name).join(' · ')}</p><p>{therapy.scope}</p></div></>:chapter===1?<PathwayMap key={therapy.id} therapy={therapy}/>:chapter===2?<Mechanism key={therapy.id} therapy={therapy}/>:<><h3>What was actually studied?</h3><Evidence therapy={therapy}/><p>How closely does the studied population match the person in this consultation?</p></>}</main><footer className={s.presentationFooter}><button disabled={chapter===0} onClick={()=>setChapter(v=>v-1)}>← Previous</button><span>{chapters[chapter]}</span><button disabled={chapter===chapters.length-1} onClick={()=>setChapter(v=>v+1)}>Next →</button></footer></div>;}
