'use client';
import {useEffect, useRef, useState} from 'react';
import catalogue from '@/data/therapy-explorer.json';
import {evidenceFor} from './evidence';
import s from './LearningTools.module.css';
type Therapy = typeof catalogue[number];
type Tab = 'mechanism'|'guide'|'compare';
const goals = [{id:'recover',label:'Recovery & tissue'},{id:'fat',label:'Body composition'},{id:'hormones',label:'Hormones & libido'},{id:'sleep',label:'Sleep'},{id:'mind',label:'Brain & cognition'},{id:'skin',label:'Skin & hair'},{id:'gut',label:'Gut health'},{id:'immunity',label:'Immune function'},{id:'longevity',label:'Longevity'}];
export default function LearningTools({therapy, initialTab, onClose, onChoose}:{therapy:Therapy;initialTab:Tab;onClose:()=>void;onChoose:(id:string)=>void}) {
 const dialog=useRef<HTMLDialogElement>(null);
 const [tab,setTab]=useState<Tab>(initialTab),[other,setOther]=useState(therapy.id==='tesamorelin'?'trt':'tesamorelin');
 useEffect(()=>{const node=dialog.current;node?.showModal();return()=>node?.close();},[]);
 return <dialog ref={dialog} className={s.dialog} onCancel={onClose} aria-labelledby="learning-title">
  <header className={s.header}><div><span>KAMURA / LEARNING STUDIO</span><h2 id="learning-title">Understand the pathway.</h2></div><button onClick={onClose} aria-label="Close learning studio">✕</button></header>
  <nav className={s.tabs} aria-label="Learning tools">{(['mechanism','guide','compare'] as Tab[]).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='mechanism'?'Explore the mechanism':t==='guide'?'Find my learning path':'Compare therapies'}</button>)}</nav>
  <div className={s.body}>
   {tab==='mechanism'&&<Mechanism key={therapy.id} therapy={therapy}/>}
   {tab==='guide'&&<Guide onChoose={id=>{onChoose(id);onClose();}}/>}
   {tab==='compare'&&<><p>Compare the question each therapy has been studied for, before comparing the claims.</p><label className={s.select}>Compare {therapy.name} with<select value={other} onChange={e=>setOther(e.target.value)}>{catalogue.filter(t=>t.id!==therapy.id).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className={s.comparison}>{[therapy,catalogue.find(t=>t.id===other)!].map(t=><article key={t.id}><h3>{t.name}</h3><p>{t.what}</p><Evidence therapy={t}/><h4>Mechanism</h4><p>{t.mechanism}</p><h4>Anatomical context</h4><p>{t.regions.map(r=>r.name).join(' · ')}</p><a href={t.references[0]?.url} target="_blank" rel="noreferrer">Read linked research ↗</a></article>)}</div></>}
  </div>
 </dialog>;
}
export function Evidence({therapy}:{therapy:Therapy}){const e=evidenceFor(therapy);return <section className={s.evidence}><span>{e.label}</span><h4>{e.outcome}</h4><p><strong>Who was studied:</strong> {e.population}</p><p>{e.finding}</p><p className={s.boundary}>{e.boundary}</p>{e.source&&<a href={e.source} target="_blank" rel="noreferrer">Read the supporting source ↗</a>}</section>;}
function Mechanism({therapy}:{therapy:Therapy}) {
 const [stage,setStage]=useState(0),[playing,setPlaying]=useState(false),[endpoint,setEndpoint]=useState(false);
 const repair=therapy.id==='bpc-157',fat=therapy.id==='tesamorelin',trt=therapy.id==='trt';
 const steps=repair?['Injured tissue','Repair signalling','Matrix remodelling']:trt?['Hormone signal','Cell response','Feedback loop']:therapy.pathway;
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{setStage(Math.min(stage+1,steps.length-1));if(stage+1>=steps.length-1)setPlaying(false);},2400);return()=>clearTimeout(timer);},[playing,stage,steps.length]);
 return <><div className={s.intro}><span>INSIDE THE BODY</span><h3>{fat?'Visceral fat, in context':repair?'From injury to tissue remodelling':trt?'A signal with a feedback loop':therapy.name}</h3><p>{fat?'Explore an abdominal cross-section and the measured endpoint of a clinical trial.':repair?'Step through a simplified repair process. The illustration explains biology; it does not show a measured BPC-157 treatment response.':trt?'Follow replacement testosterone to the cell, then trace the feedback to the brain and testes.':therapy.mechanism}</p></div>
  <div className={s.visual}>
   {fat?<><svg viewBox="0 0 600 300" role="img" aria-label={`Schematic abdominal cross-section. ${endpoint?'Trial endpoint':'Baseline'} with visceral fat highlighted.`}><ellipse cx="300" cy="145" rx="210" ry="125" fill="#e8c6a0" stroke="#8c5143" strokeWidth="9"/><ellipse cx="300" cy="145" rx="174" ry="94" fill="#f6eee4" stroke="#b46a61" strokeWidth="15"/>{Array.from({length:18},(_,i)=>{const a=i*Math.PI*2/18;return <circle key={i} cx={300+112*Math.cos(a)} cy={145+61*Math.sin(a)} r={endpoint?17*Math.sqrt(.848):17} fill="#d79f3d"/>;})}<path d="M255 104 C355 83 365 137 267 143 S249 200 335 181" fill="none" stroke="#a96e6d" strokeWidth="20" strokeLinecap="round"/><text x="300" y="286" textAnchor="middle">Gold: visceral fat • Outer ring: subcutaneous fat</text></svg><div className={s.controls}><button aria-pressed={!endpoint} onClick={()=>setEndpoint(false)}>Baseline</button><button aria-pressed={endpoint} onClick={()=>setEndpoint(true)}>26-week trial endpoint</button></div><div className={s.results}><div><strong>{endpoint?'84.8':'100'}</strong><span>Tesamorelin group</span></div><div><strong>{endpoint?'105.0':'100'}</strong><span>Placebo group</span></div></div><p>Visceral fat area indexed to 100 at baseline. Two measured endpoints; no intermediate trajectory is implied. Diagram is schematic, not a scan.</p></>:
    repair?<svg viewBox="0 0 600 290" role="img" aria-label={`Tissue repair illustration: ${steps[stage]}`}><rect x="40" y="65" width="520" height="145" rx="65" fill="#c68579"/>{Array.from({length:7},(_,i)=><path key={i} d={`M65 ${82+i*18} Q170 ${69+i*18} 265 ${82+i*18} M${stage===2?265:335} ${82+i*18} Q430 ${96+i*18} 538 ${82+i*18}`} fill="none" stroke={stage===2?'#f1d8ba':'#efd0ba'} strokeWidth="5"/>)}{stage<2&&<path d="M285 68 L308 95 L287 126 L316 156 L293 206" stroke="#702f33" strokeWidth="12" fill="none"/>}{stage===1&&Array.from({length:9},(_,i)=><circle key={i} cx={258+(i%3)*38} cy={85+Math.floor(i/3)*47} r="7" fill="#e4b553"/>)}<text x="300" y="260" textAnchor="middle">{steps[stage]} · schematic, no elapsed-time scale</text></svg>:
    <svg viewBox="0 0 600 260" role="img" aria-label={`${therapy.name}: ${steps[stage]}`}><path d="M120 115 H480" stroke="#ad9b87" strokeWidth="3" strokeDasharray="6 8"/>{steps.map((_,i)=><g key={i}><circle cx={110+i*(380/Math.max(1,steps.length-1))} cy="115" r="48" fill={stage===i?'#2c635c':'#dfd6c8'} stroke="#fff" strokeWidth="4"/><text x={110+i*(380/Math.max(1,steps.length-1))} y="122" textAnchor="middle" fill={stage===i?'white':'#40382f'}>{i+1}</text></g>)}{trt&&stage===2&&<path d="M490 167 Q300 257 110 167" fill="none" stroke="#a44d4d" strokeWidth="4" strokeDasharray="8 5"/>}<text x="300" y="245" textAnchor="middle">{trt&&stage===2?'Negative feedback reduces upstream signalling':'Signal → target → biological response'}</text></svg>}
  </div>
  {!fat&&<><div className={s.controls}>{steps.map((step,i)=><button key={step} aria-pressed={stage===i} onClick={()=>{setStage(i);setPlaying(false);}}>{i+1}. {step}</button>)}<button onClick={()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setStage(v=>(v+1)%steps.length);setPlaying(false);return;}if(stage===steps.length-1)setStage(0);setPlaying(v=>!v);}}>{playing?'Pause':'Play sequence'}</button></div><p className={s.stageText} aria-live="polite">{repair?['An injury disrupts the tissue matrix. This is the starting context for repair research.','Repair involves coordinated cell migration, inflammatory signals and blood supply. BPC-157 research examines parts of this process, mainly in animals.','New matrix is deposited and reorganised. This drawing does not establish that BPC-157 restores normal tissue or shortens recovery in humans.'][stage]:trt?['Testosterone circulates to multiple tissues. Replacement adds an external source to this system.','Androgen receptors translate the hormone signal into changes in cell activity. Clinical response depends on the starting condition and the outcome measured.','External testosterone can suppress LH and FSH signalling and sperm production. Fertility goals therefore change the treatment discussion.'][stage]:steps[stage]}</p></>}
  <Evidence therapy={therapy}/><h4>Ask a better question</h4><p>{repair?'Was healing measured in human tendon, or inferred from animal tissue and pain reports?':fat?'Was the fat measured around the organs, under the skin, or as total body weight?':trt?'Does the evidence apply to confirmed deficiency, and how will symptoms, hormone levels and fertility goals be assessed?':'Did the study measure a patient outcome, a blood marker, or a cell response—and did it test this exact compound and formulation?'}</p>
 </>;
}
function Guide({onChoose}:{onChoose:(id:string)=>void}) {
 const [goal,setGoal]=useState(''),[intent,setIntent]=useState(''),[focus,setFocus]=useState(''),[copied,setCopied]=useState('');
 const result=!!(goal&&intent&&focus);const matches=catalogue.filter(t=>t.goals.includes(goal));
 const notes=`My Kamura learning plan\nTopic: ${goals.find(g=>g.id===goal)?.label}\nStarting point: ${intent}\nFocus: ${focus}\n\nQuestions to explore:\n• What outcome was measured, and in whom?\n• Is this evidence for the exact compound, route and combination?\n• What would count as a meaningful change?\n• What should be monitored, and when should the plan be reassessed?`;
 return <><div className={s.intro}><span>THREE SHORT QUESTIONS</span><h3>What would you like to understand?</h3><p>Build a reading path and a question list. Answers stay in this open session.</p></div><fieldset><legend>1. Choose a topic</legend><div className={s.controls}>{goals.map(g=><button key={g.id} aria-pressed={goal===g.id} onClick={()=>{setGoal(g.id);setCopied('');}}>{g.label}</button>)}</div></fieldset>{goal&&<fieldset><legend>2. Where are you starting?</legend><div className={s.controls}>{['Just exploring','Preparing for a consultation','Understanding a current treatment'].map(x=><button key={x} aria-pressed={intent===x} onClick={()=>{setIntent(x);setCopied('');}}>{x}</button>)}</div></fieldset>}{intent&&<fieldset><legend>3. What matters most today?</legend><div className={s.controls}>{['How the signal works','What benefits were measured','What to ask and track'].map(x=><button key={x} aria-pressed={focus===x} onClick={()=>{setFocus(x);setCopied('');}}>{x}</button>)}</div></fieldset>}{result&&<section className={s.plan} aria-live="polite"><h3>Your learning path</h3><p>{focus==='How the signal works'?'Start with the mechanism viewer, then connect the pathway to the mapped anatomy.':focus==='What benefits were measured'?'Start with the outcome and study population, then open the original research.':'Start by defining the outcome you care about and a question list for your next discussion.'} {intent==='Understanding a current treatment'?'Use your existing care plan to identify what is already being monitored.':intent==='Preparing for a consultation'?'Bring the question list to your consultation.':'Explore one mechanism at a time before comparing compounds.'}</p><p>These are topics in the library, not a ranked treatment selection.</p><div className={s.controls}>{matches.map(t=><button key={t.id} onClick={()=>onChoose(t.id)}>Explore {t.name} ↗</button>)}</div><h4>Your discussion checklist</h4>{notes.split('\n').filter(x=>x.startsWith('•')).map(x=><p key={x}>{x}</p>)}{goal==='hormones'&&<p>Include a question about fertility goals and how a hormone diagnosis was established.</p>}<button className={s.solid} onClick={async()=>{try{await navigator.clipboard.writeText(notes);setCopied('Learning plan copied');}catch{setCopied('Copy is unavailable. Select the question list above to save it.');}}}>Copy my learning plan</button><span role="status"> {copied}</span><button onClick={()=>{setGoal('');setIntent('');setFocus('');setCopied('');}}>Start again</button></section>}</>;
}
