'use client';
import { useEffect, useMemo, useState } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { Search, X, ArrowRight, ArrowLeft, ArrowUpRight, RotateCcw, RotateCw, Pause, Play, Focus, Layers, BookOpen, ChevronDown, Network, CircleHelp } from 'lucide-react';
import catalogue from '@/data/therapy-explorer.json';
import { DEFAULT_VISIBLE, SYSTEMS, type Atlas, type Concept, type SceneState, type SystemId } from './anatomy';
import styles from './TherapyExplorer.module.css';
const AnatomyScene=dynamic(()=>import('./scene'),{ssr:false});
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const categories=['All',...Array.from(new Set(catalogue.map(t=>t.category)))];
const stages=['Body map','Mechanism','Research'] as const;
const combinations=[
 {name:'Wolverine',ids:['bpc-157','tb-500']}, {name:'Glow',ids:['bpc-157','ghk-cu','tb-500']},
 {name:'Healing & Recovery',ids:['bpc-157','ghk-cu','thymosin-alpha-1','tb-500']},
 {name:'Athlete Recovery',ids:['bpc-157','ghk-cu','cjc-ipamorelin']},
 {name:'Body Composition',ids:['cjc-ipamorelin','aod-9604']},
 {name:'Recovery + GH',ids:['cjc-ipamorelin','bpc-157']},
 {name:'Mitochondrial',ids:['nad','mots-c']}, {name:'Longevity Sleep',ids:['epithalon','dsip']},
 {name:'Hormonal Reset',ids:['kisspeptin-10','thymosin-alpha-1']},
 {name:'Cognitive Dual',ids:['semax','selank']}, {name:'Immune + Cognitive',ids:['thymosin-alpha-1','selank']},
 {name:'Gut (oral)',ids:['bpc-157','kpv','ll-37']},
];
export default function TherapyExplorer(){
 const [atlas,setAtlas]=useState<Atlas|null>(null),[scene,setScene]=useState<SceneState>(initial);
 const [progress,setProgress]=useState(0),[error,setError]=useState('');
 const [selectedId,setSelectedId]=useState('tesamorelin'),[stage,setStage]=useState(0),[regionIndex,setRegionIndex]=useState(0),[playing,setPlaying]=useState(false);
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[library,setLibrary]=useState<'therapies'|'combinations'>('therapies');
 const [mobileLibrary,setMobileLibrary]=useState(false),[panelOpen,setPanelOpen]=useState(true),[layers,setLayers]=useState(false),[credits,setCredits]=useState(false),[anatomyQuery,setAnatomyQuery]=useState('');
 const [inspected,setInspected]=useState<Concept|null>(null),[selectedCombination,setSelectedCombination]=useState<string|null>(null);
 const therapy=catalogue.find(t=>t.id===selectedId)!;
 const filtered=catalogue.filter(t=>(category==='All'||t.category===category)&&`${t.name} ${t.title} ${t.category}`.toLowerCase().includes(query.toLowerCase()));
 const activeCombination=combinations.find(c=>c.name===selectedCombination);
 const allMappedIds=useMemo(()=>Array.from(new Set((activeCombination?catalogue.filter(t=>activeCombination.ids.includes(t.id)):[therapy]).flatMap(t=>t.regions.flatMap(r=>r.elements)))),[therapy,activeCombination]);
 const anatomyResults=useMemo(()=>atlas&&anatomyQuery.trim()?atlas.concepts.filter(c=>c.name.toLowerCase().includes(anatomyQuery.toLowerCase())).slice(0,25):[],[atlas,anatomyQuery]);
 useEffect(()=>{const abort=new AbortController();fetch('/body-models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('The anatomy library could not be loaded.');return r.json();}).then(setAtlas).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{if(!playing)return;const media=matchMedia('(prefers-reduced-motion: reduce)');if(media.matches){setPlaying(false);return;}const timer=setInterval(()=>setRegionIndex(i=>(i+1)%therapy.regions.length),4500);return()=>clearInterval(timer);},[playing,therapy]);
 useEffect(()=>{if(!atlas)return;const ids=stage===1?therapy.regions[regionIndex]?.elements:allMappedIds;setScene(s=>({...s,selected:ids??[],isolate:stage===1,explode:0,rotate:false,reset:s.reset+1}));setInspected(null);},[atlas,therapy,stage,regionIndex,allMappedIds]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobileLibrary(false);setLayers(false);setCredits(false);setPlaying(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const choose=(id:string,keepCombination=false)=>{setSelectedId(id);setStage(0);setRegionIndex(0);setPlaying(false);setInspected(null);setPanelOpen(true);setMobileLibrary(false);if(!keepCombination)setSelectedCombination(null);history.replaceState(null,'',`/body?t=${id}`);};
 // Shareable deep links: /body?t=<therapy-id> opens that therapy directly.
 useEffect(()=>{const id=new URLSearchParams(location.search).get('t');if(id&&id!==selectedId&&catalogue.some(t=>t.id===id))choose(id);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 const focusRegion=(i:number)=>{setRegionIndex(i);setStage(1);setPanelOpen(true);setInspected(null);};
 const inspect=(id:string)=>{const p=atlas?.parts.find(p=>p.id===id);if(!p)return;setPlaying(false);setInspected({id:p.conceptId,name:p.name,elements:[p.id]});setScene(s=>({...s,selected:[p.id],isolate:false,rotate:false}));setPanelOpen(true);};
 const reset=()=>{setPlaying(false);setStage(0);setInspected(null);setScene(s=>({...initial,selected:allMappedIds,reset:s.reset+1}));};
 return <div className={styles.explorer} data-lenis-prevent>
  <div className={styles.sceneWrap}>{atlas&&<AnatomyScene atlas={atlas} state={{...scene,inspectorOpen:panelOpen}} onSelect={inspect} onProgress={setProgress} onError={setError}/>}</div>
  <header className={styles.header}>
   <Link href="/" className={styles.brand}>KAMURA<span>PREVENTION · LONGEVITY</span></Link>
   <div className={styles.headerTitle}>The body, connected.</div>
   <div className={styles.headerActions}><button onClick={()=>setMobileLibrary(v=>!v)} className={styles.libraryToggle}><Search size={17}/>Therapies</button><button onClick={()=>setCredits(true)} aria-label="Sources and model information"><CircleHelp size={20}/></button><Link href="/">Back to Kamura <ArrowUpRight size={14}/></Link></div>
  </header>
  <aside className={`${styles.library} ${mobileLibrary?styles.libraryOpen:''}`} aria-label="Therapy library">
   <div className={styles.libraryHeading}><span>Explore therapies</span><button className={styles.mobileClose} onClick={()=>setMobileLibrary(false)} aria-label="Close therapy library"><X size={20}/></button><span className={styles.count}>{catalogue.length}</span></div>
   <div className={styles.libraryTabs}><button aria-pressed={library==='therapies'} onClick={()=>setLibrary('therapies')}>Therapies</button><button aria-pressed={library==='combinations'} onClick={()=>setLibrary('combinations')}>Combinations</button></div>
   {library==='therapies'?<><label className={styles.search}><Search size={16}/><input aria-label="Search therapies" placeholder="Peptide, hormone, pathway…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear therapy search"><X size={15}/></button>}</label><label className={styles.category}><span className={styles.srOnly}>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label><div className={styles.therapyList}>{filtered.map(t=><button className={styles.therapyRow} key={t.id} aria-pressed={t.id===selectedId&&!activeCombination} onClick={()=>choose(t.id)}><span className={styles.therapyDot}/><span><strong>{t.name}</strong><small>{t.kind}</small></span><ArrowRight size={14}/></button>)}{filtered.length===0&&<p className={styles.empty}>No therapies match this search.</p>}</div></>:<div className={styles.therapyList}><p className={styles.listIntro}>Explore constituent pathways together.</p>{combinations.map(c=><button key={c.name} className={styles.comboRow} aria-pressed={activeCombination?.name===c.name} onClick={()=>{setSelectedCombination(c.name);choose(c.ids[0],true);}}><strong>{c.name}</strong><span>{c.ids.map(id=>catalogue.find(t=>t.id===id)?.name).join(' · ')}</span><small>{c.ids.length} therapies <ArrowRight size={13}/></small></button>)}</div>}
   <div className={styles.libraryFoot}><BookOpen size={15}/><span>Research linked for every therapy</span></div>
  </aside>
  <div className={styles.stageNav} aria-label="Explorer views">{stages.map((label,i)=><button key={label} aria-pressed={stage===i} onClick={()=>{setStage(i);setInspected(null);setPanelOpen(true);setPlaying(false);}}><span>0{i+1}</span>{label}</button>)}</div>
  {!panelOpen&&<button className={styles.reopen} onClick={()=>setPanelOpen(true)}><BookOpen size={17}/>Open {therapy.name}</button>}
  {panelOpen&&<aside className={`${styles.detail} detail-sheet`} aria-label={`${therapy.name} details`}>
   <div className={styles.detailHeading}><div><span className={styles.eyebrow}>{inspected?'ANATOMY':therapy.category}</span><h1>{inspected?inspected.name:therapy.name}</h1></div><button onClick={()=>{setPanelOpen(false);setPlaying(false);}} aria-label="Close therapy details"><X size={20}/></button></div>
   <div className={styles.detailScroll}>
    {inspected?<><p className={styles.lead}>Selected structure</p><p className={styles.text}>{inspected.id}</p><button className={styles.primary} onClick={()=>setScene(s=>({...s,isolate:!s.isolate,reset:s.reset+1}))}><Focus size={16}/>{scene.isolate?'Show body context':'Focus on structure'}</button><button className={styles.outline} onClick={reset}>Return to {therapy.name}</button></>:<>
    <span className={styles.researchBadge}>{therapy.researchContext}</span>
    {activeCombination&&<section className={styles.comboSelection}><span className={styles.eyebrow}>{activeCombination.name}</span><div>{activeCombination.ids.map(id=><button key={id} aria-pressed={selectedId===id} onClick={()=>choose(id,true)}>{catalogue.find(t=>t.id===id)?.name}</button>)}</div><p>Shared anatomical context. Combined efficacy is a separate research question.</p></section>}
    {stage!==2?<><h2 className={styles.editorial}>{therapy.title}</h2><p className={styles.lead}>{therapy.mechanism}</p>
    {stage===0?<section className={styles.regionList}><h3>Explore the relevant anatomy</h3>{therapy.regions.map((r,i)=><button key={r.id} onClick={()=>focusRegion(i)}><span>0{i+1}</span><strong>{r.name}</strong><Focus size={15}/></button>)}</section>:<><section className={styles.pathway}><div className={styles.sectionLabel}><Network size={15}/>Signaling overview</div>{therapy.pathway.map((node,i)=><div key={node} className={`${styles.pathNode} ${playing?styles.pathPlaying:''}`} style={{animationDelay:`${i*.45}s`}}><span>{i+1}</span><p>{node}</p>{i<2&&<ArrowRight size={15}/>}</div>)}</section><section className={styles.regionList}><h3>Move through the anatomy</h3>{therapy.regions.map((r,i)=><button key={r.id} aria-pressed={regionIndex===i} onClick={()=>focusRegion(i)}><span>0{i+1}</span><strong>{r.name}</strong><Focus size={15}/></button>)}</section><div className={styles.playback}><button aria-label="Previous structure" onClick={()=>setRegionIndex(i=>(i+therapy.regions.length-1)%therapy.regions.length)}><ArrowLeft size={16}/></button><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause tour':'Play anatomy tour'}</button><button aria-label="Next structure" onClick={()=>setRegionIndex(i=>(i+1)%therapy.regions.length)}><ArrowRight size={16}/></button></div></>}
    <details className={styles.scope}><summary>About this visual</summary><p>{therapy.scope}</p></details>
    <button className={styles.researchLink} onClick={()=>{setStage(2);setPlaying(false);}}><BookOpen size={17}/><span>{therapy.references.length} linked research articles</span><ArrowRight size={16}/></button>
    {therapy.treatmentSlug&&<Link className={styles.researchLink} href={`/treatments/${therapy.treatmentSlug}`}><ArrowUpRight size={17}/><span>Kamura Score &amp; full evidence breakdown</span><ArrowRight size={16}/></Link>}
    </>:<section className={styles.researchList}><h2 className={styles.editorial}>Read the research.</h2><p className={styles.text}>Article records from PubMed via Europe PMC. Open a paper to inspect its methods, population, and findings.</p>{therapy.references.map(r=><article key={r.pmid}><div className={styles.articleMeta}><span>{r.year}</span><span>{r.types.includes('Randomized Controlled Trial')?'Randomized trial':r.types.includes('Systematic Review')?'Systematic review':r.types.includes('Review')?'Review':'Research article'}</span></div><a href={r.url} target="_blank" rel="noreferrer"><h3>{r.title}</h3><ArrowUpRight size={16}/></a><p>{r.journal}</p><span className={styles.pmid}>PMID {r.pmid}</span>{r.doi&&<a className={styles.doi} href={`https://doi.org/${r.doi}`} target="_blank" rel="noreferrer">Publisher <ArrowUpRight size={12}/></a>}</article>)}{therapy.treatmentSlug&&<Link className={styles.researchLink} href={`/treatments/${therapy.treatmentSlug}`}><ArrowUpRight size={17}/><span>Kamura Score &amp; full evidence breakdown</span><ArrowRight size={16}/></Link>}<a className={styles.moreResearch} href={`https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(therapy.name.replace(' / ',' OR '))}`} target="_blank" rel="noreferrer">Find more research <ArrowUpRight size={15}/></a><p className={styles.retrieved}>References retrieved {therapy.retrieved}</p></section>}
    </>}
   </div>
   {!inspected&&<div className={styles.detailFoot}><span>{therapy.kind}</span><span>{therapy.regions.length} mapped regions</span></div>}
  </aside>}
  <div className={styles.bottomDock}><button onClick={()=>setLayers(v=>!v)} aria-expanded={layers}><Layers size={18}/><span>Layers</span></button><div><label htmlFor="body-separate">Separate anatomy <output>{Math.round(scene.explode*100)}%</output></label><input id="body-separate" type="range" min="0" max="100" value={scene.explode*100} onChange={e=>{setPlaying(false);setScene(s=>({...s,isolate:false,explode:Number(e.target.value)/100,rotate:false}));}}/></div><button aria-label={scene.rotate?'Pause body rotation':'Rotate body'} disabled={scene.isolate||scene.explode>=.4} onClick={()=>setScene(s=>({...s,rotate:!s.rotate}))}>{scene.rotate?<Pause size={18}/>:<RotateCw size={18}/>}</button><button onClick={reset} aria-label="Reset body view"><RotateCcw size={18}/></button></div>
  {layers&&<section className={styles.layersPanel} aria-label="Anatomy controls"><div className={styles.libraryHeading}>Anatomy layers<button onClick={()=>setLayers(false)} aria-label="Close anatomy controls"><X size={18}/></button></div><label className={styles.search}><Search size={15}/><input placeholder="Find any structure…" aria-label="Search anatomy" value={anatomyQuery} onChange={e=>setAnatomyQuery(e.target.value)}/></label>{anatomyQuery?<div className={styles.anatomyMatches}>{anatomyResults.map(c=><button key={c.id} onClick={()=>{setInspected(c);setScene(s=>({...s,selected:c.elements,isolate:true,reset:s.reset+1}));setLayers(false);setPanelOpen(true);setPlaying(false);}}>{c.name}<Focus size={14}/></button>)}{!anatomyResults.length&&<p>No structures found.</p>}</div>:<>{SYSTEMS.map(s=><label className={styles.system} key={s.id}><span style={{background:s.color}}/>{s.name}<input type="checkbox" checked={scene.visible.includes(s.id)} onChange={()=>{setPlaying(false);setScene(v=>({...v,isolate:false,selected:[],visible:v.visible.includes(s.id)?v.visible.filter(id=>id!==s.id):[...v.visible,s.id as SystemId]}));}}/></label>)}<button className={styles.outline} onClick={()=>setScene(s=>({...s,visible:DEFAULT_VISIBLE,isolate:false,selected:[]}))}>Restore all systems</button></>}</section>}
  <div className={styles.sceneCaption}>{scene.isolate?(inspected?.name??therapy.regions[regionIndex]?.name):activeCombination?.name??therapy.name}<span>{scene.isolate?'ANATOMICAL FOCUS':'DRAG TO ROTATE · SCROLL TO ZOOM'}</span></div>
  {progress<100&&!error&&<div className={styles.loading} role="status"><strong>Preparing the body</strong><span>{progress}% · Loading anatomical structures</span><progress max={100} value={progress}/></div>}
  {error&&<div className={styles.loading} role="alert"><strong>Unable to load anatomy</strong><p>{error}</p><button className={styles.primary} onClick={()=>location.reload()}>Reload</button></div>}
  {credits&&<div className={styles.credits}><div><button className={styles.closeCredit} aria-label="Close sources" onClick={()=>setCredits(false)}><X size={22}/></button><span className={styles.eyebrow}>SOURCES & MODEL</span><h2>Built on open science.</h2><p>Adult male reference anatomy: BodyParts3D, © DBCLS, CC BY 4.0. The source contains 2,234 meshes; cellular structures and visceral-fat compartments are not included.</p><p>Rendering adapted from Human Atlas by ashemag under the MIT License. Kamura adds therapy mapping, research records, and the visual learning experience.</p><a href="/body-models/ATTRIBUTION.md" target="_blank" rel="noreferrer">Anatomy attribution <ArrowUpRight size={14}/></a><a href="/body-models/VIEWER-LICENSE.txt" target="_blank" rel="noreferrer">Viewer license <ArrowUpRight size={14}/></a><a href="https://europepmc.org/" target="_blank" rel="noreferrer">Europe PMC research database <ArrowUpRight size={14}/></a></div></div>}
 </div>;
}
