 'use client';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {PEPTIDE_GOALS} from '@/data/peptides';
import catalogue from '@/data/therapy-explorer.json';
import {peptideContexts,therapyMatches} from '@/lib/peptide-learning';
import s from '@/components/peptides/PeptideLearning.module.css';
export default function PeptideDirectoryContent(){const params=useSearchParams();const [query,setQuery]=useState(params.get('q')||''),[category,setCategory]=useState('All'),[goal,setGoal]=useState(params.get('goal')||'');const results=catalogue.filter(t=>(category==='All'||t.category===category)&&(!goal||PEPTIDE_GOALS.find(g=>g.id===goal)?.slugs.some(slug=>slug===t.id||slug===t.treatmentSlug))&&therapyMatches(t.id,query)).sort((a,b)=>a.name.localeCompare(b.name));return <div className={s.page}><div className={s.container}><div className={s.directoryFilters}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a peptide or concern" aria-label="Search peptides and concerns"/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Therapy category"><option>All</option>{Array.from(new Set(catalogue.map(x=>x.category))).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Learning goal" value={goal} onChange={e=>setGoal(e.target.value)}><option value="">All learning goals</option>{PEPTIDE_GOALS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></div><p role="status">{results.length} guides · Includes related non-peptide therapies, identified in their profiles.</p><div className={s.directoryGrid}>{results.map(t=><Link key={t.id} href={`/peptides/${t.id}`} className={s.directoryCard}><span className={s.eyebrow}>{t.category}</span><h2>{t.name}</h2><p>{peptideContexts[t.id].intro}</p><small>{peptideContexts[t.id].topics[0].status}</small><strong>Explore the visual guide ↗</strong></Link>)}</div>{!results.length&&<div className={s.outcome}><h2>No matching guide</h2><button className={s.primary} onClick={()=>{setQuery('');setCategory('All');setGoal('');}}>Reset filters</button></div>}</div></div>;}
